### ISSUE TITLE
maybe safer to default to dryrun mode

### ISSUE THREAD

**Issue by juhp** [holmgr/cargo-sweep#61]
How about making dry-run the default mode and instead having a `--delete` option say to enable actual deletion?

That might be a friendlier approach: generally I like to see the affect of running such a command first before doing the deleting.

(Also in the unix-like world `-n` is a common short form option for dry-run.)

**Comment by jyn514** [comment]
I don't think there's a need for dry-run to be the default; the worst this can do (barring bugs) is make you have to spend time recompiling, and you already have to think about the options at least a bit because `cargo sweep` without arguments gives an error.

I agree it would have been nice to use `-n` originally, but given that `-d` already exists I don't think there's a need for both.
