### ISSUE TITLE
Accept more than one project

### ISSUE THREAD

**Issue by marcospb19** [holmgr/cargo-sweep#95]
Currently, `cargo sweep` accepts one optional and positional argument as path to the project to `sweep`.

It would be good to have it accepting multiple paths.

```
cargo sweep [OPTS] project1 project2 project3
```

`cargo-sweep` is already capable of sweeping multiple projects (see `--recursive` implementation), so this _should_ be easy to implement.

**Comment by jyn514** [comment]
Mentoring instructions: Change https://github.com/holmgr/cargo-sweep//blob/475ac9ec16518596fc21cb2ea77bd8045b5a4a6d/src/cli.rs#L39-L40 to a Vec instead of Option, then change https://github.com/holmgr/cargo-sweep//blob/a36602ffb06c2b62f35d246e22dc33b5163a69b0/src/main.rs#L154-L160 to support multiple paths. I think everything else should "just work"

**Comment by social-anthrax** [comment]
I've added some basic support but it only writes the timestamp into the first path. I'm assuming this isn't expected behaviour but I can't say i've used it enough to know what would be correct.

**Comment by jyn514** [comment]
@social-anthrax that's amazing, thank you! I think for now we can give a hard error if you try to combine `--stamp` with either `--recursive` or multiple projects.

**Comment by social-anthrax** [comment]
Recursive should still work fine as it'll save it to the root. I've added a check to make sure `--stamp` isn't set when multiple paths are passed.
